name: "Continuous Integration"

on:
  pull_request:
    paths-ignore:
      - "*.md"
  push:
    branches-ignore:
      - 'dependabot/**'
  release:
    types: [created]
  workflow_dispatch: ~

  workflow_call:
    inputs:
      php-versions:
        description: "The PHP versions to use when running the job"
        default: '["7.2", "7.3", "7.4", "8.0", "8.1"]'
        required: false
        type: "string"
      composer-options:
        description: "Additional flags for the composer install command."
        default: "--prefer-dist"
        required: false
        type: "string"

env:
  fail-fast: true

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version: "${{ fromJson(inputs.php-versions) }}"
        dependencies:
          - "highest"
        include:
          - php-version: "${{ fromJson(inputs.php-versions)[0] }}"
            dependencies: "lowest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "${{ inputs.composer-options }}"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"
